// ============================================================================
// PwaLinks (server component; rendered in the root layout, hoisted to <head>)
//
// iOS does not read the web manifest for launch images or favicons, so the
// apple-touch-startup-image links have to be real <link> tags. The table comes
// from lib/pwa-splash.ts, generated by scripts/generate-pwa-assets.mjs so
// markup and asset dimensions can never drift apart.
// ============================================================================
import { SPLASHES } from "@/lib/pwa-splash";

export default function PwaLinks() {
  return (
    <>
      {SPLASHES.map((s) => (
        <link key={s.href} rel="apple-touch-startup-image" media={s.media} href={s.href} />
      ))}
    </>
  );
}