// Generated by scripts/generate-pwa-assets.mjs - do not edit by hand.
// iOS apple-touch-startup-image media-query table (portrait launch screens).
export type SplashEntry = { href: string; media: string };
export const SPLASHES: SplashEntry[] = [
  {
    "href": "/splash/splash-640x1136.png",
    "media": "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "href": "/splash/splash-750x1334.png",
    "media": "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "href": "/splash/splash-828x1792.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "href": "/splash/splash-1125x2436.png",
    "media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "href": "/splash/splash-1242x2688.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "href": "/splash/splash-1170x2532.png",
    "media": "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "href": "/splash/splash-1284x2778.png",
    "media": "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "href": "/splash/splash-1179x2556.png",
    "media": "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "href": "/splash/splash-1284x2796.png",
    "media": "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "href": "/splash/splash-1536x2048.png",
    "media": "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "href": "/splash/splash-1668x2224.png",
    "media": "(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "href": "/splash/splash-1668x2388.png",
    "media": "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "href": "/splash/splash-2048x2732.png",
    "media": "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "href": "/splash/splash-1620x2160.png",
    "media": "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "href": "/splash/splash-1640x2360.png",
    "media": "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "href": "/splash/splash-1488x2266.png",
    "media": "(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2)"
  }
];
